#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=01:00:00
#PBS -N maxfilter

# PBS is a computer software that performs job-scheduling
# Copyright (c) 2020 brainlife.io at University of Texas at Austin and Indiana U
#
# This is the main file run by the brainlife.io orchestration system
#
# Author: Franco Pestilli


set -e
set -x

# Make output directory
#mkdir -p out_dir

# Run the actual python code
# singularity exec docker://brainlife/mne:latest python3 bad-channels.py  # mne version: 0.19 can't read my .fif file

# Test local
python3 ./bad-channels.py