#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=01:00:00
#PBS -N bad-channels

# PBS is a computer software that performs job-scheduling
# Copyright (c) 2020 brainlife.io at University of Texas at Austin and Indiana U
#
# This is the main file run by the brainlife.io orchestration system
#
# Author: Franco Pestilli


set -e
set -x

# Make output directories
mkdir -p out_dir_bad_channels
mkdir -p out_dir_report

# Run the actual python code
#singularity exec docker://brainlife/mne:0.22.0 python3 bad-channels.py

# Test local
#python3 ./bad-channels.py
#singularity exec -e -B /network/lustre/iss01/cenir/analyse/meeg/BRAINLIFE/aurore docker://brainlife/mne:0.22.0 python3 bad-channels.py .