#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=01:00:00
#PBS -N bad-channels

# PBS is a computer software that performs job-scheduling
# Copyright (c) 2020 brainlife.io at University of Texas at Austin and Indiana U
#
# This is the main file run by the brainlife.io orchestration system
#
# Author: Franco Pestilli


set -e
set -x

# Make output directories
mkdir -p out_dir_bad_channels
mkdir -p out_dir_report

# Run the actual python code
singularity exec docker://brainlife/mne:0.23dev python3 find_bad_channels.py

# Delete the bids folder
rm -r bids
